### ISSUE TITLE
Como joga?

### ISSUE THREAD

**Issue by MarlisonSilva** [mosiah-adam/sombra#1]
Gostei, mas poderia colocar no README como faz para jogar... 🤔

**Comment by akemi-adam** [comment]
True. É só que eu não disponibizei em nenhum lugar pra download
SKKSKSKSKSK. Só tem no meu drive.

Em seg, 14 de fev de 2022 9:13 AM, Marlison S. S. ***@***.***>
escreveu:

**Comment by MarlisonSilva** [comment]
Agora sim
